"""add intelligence tables product comparable newprice embedding

Revision ID: ebfc16bbbee6
Revises: a2b3c4d5e6f7
Create Date: 2026-03-26 23:35:56.082249

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebfc16bbbee6'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension exists before creating VECTOR columns.
    # This is the migration-safe path — does not depend on app startup order.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_key', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('valuation_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('product_key')
    )
    op.create_table('market_comparable',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_key', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('listing_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price_sek', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('flagged', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('flag_reason', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('disappeared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_key'], ['product.product_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_url')
    )
    op.create_index('idx_comparable_product_active', 'market_comparable', ['product_key', 'is_active'], unique=False)
    op.create_index(op.f('ix_market_comparable_is_active'), 'market_comparable', ['is_active'], unique=False)
    op.create_index(op.f('ix_market_comparable_last_seen'), 'market_comparable', ['last_seen'], unique=False)
    op.create_index(op.f('ix_market_comparable_product_key'), 'market_comparable', ['product_key'], unique=False)
    op.create_table('new_price_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_key', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('price_sek', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), server_default='SEK', nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_key'], ['product.product_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_new_price_product', 'new_price_snapshot', ['product_key', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_new_price_snapshot_product_key'), 'new_price_snapshot', ['product_key'], unique=False)
    op.create_table('product_embedding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_key', sa.String(), nullable=False),
    sa.Column('valuation_id', sa.String(), nullable=True),
    sa.Column('image_hash', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_key'], ['product.product_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_embedding_verified', 'product_embedding', ['verified'], unique=False, postgresql_where='verified = true')
    op.create_index(op.f('ix_product_embedding_product_key'), 'product_embedding', ['product_key'], unique=False)
    op.execute("CREATE INDEX idx_embedding_cosine ON product_embedding USING hnsw (embedding vector_cosine_ops)")
    op.add_column('valuations', sa.Column('product_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_valuations_product_key'), 'valuations', ['product_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_product_key'), table_name='valuations')
    op.drop_column('valuations', 'product_key')
    op.execute("DROP INDEX IF EXISTS idx_embedding_cosine")
    op.drop_index(op.f('ix_product_embedding_product_key'), table_name='product_embedding')
    op.drop_index('idx_embedding_verified', table_name='product_embedding', postgresql_where='verified = true')
    op.drop_table('product_embedding')
    op.drop_index(op.f('ix_new_price_snapshot_product_key'), table_name='new_price_snapshot')
    op.drop_index('idx_new_price_product', table_name='new_price_snapshot')
    op.drop_table('new_price_snapshot')
    op.drop_index(op.f('ix_market_comparable_product_key'), table_name='market_comparable')
    op.drop_index(op.f('ix_market_comparable_last_seen'), table_name='market_comparable')
    op.drop_index(op.f('ix_market_comparable_is_active'), table_name='market_comparable')
    op.drop_index('idx_comparable_product_active', table_name='market_comparable')
    op.drop_table('market_comparable')
    op.drop_table('product')
    # ### end Alembic commands ###
